#!/usr/bin/env python3
"""Build the Cisco API tube-style map.

Generated by batch generator. 
"""

import sys
from pathlib import Path

sys.path.insert(0, "/Users/kinlane/GitHub/all/.claude/skills")
from _subway_engine import build_subway  # noqa: E402

ABBREV = {

}

LINES = [
    {
        "name": 'Cisco Networking',
        "color": '#00BCEB',
        "stations": [
        ('Meraki', (260, 200)),
        ('Catalyst Center', (440, 175)),
        ('ACI', (620, 165)),
        ('ISE', (800, 175)),
        ('Intersight', (980, 200)),
        ],
    },
    {
        "name": 'Cisco Apps',
        "color": '#1E5BD0',
        "closed": True,
        "stations": [
        ('Webex', (820, 530)),
        ('SD-WAN', (910, 600)),
        ('ThousandEyes', (730, 600)),
        ],
    },
]

URL_OVERRIDES = {
    'Meraki': 'https://apis.apis.io/apis/cisco/meraki-api/',
    'Webex': 'https://apis.apis.io/apis/cisco/webex-api/',
    'Catalyst Center': 'https://apis.apis.io/apis/cisco/catalyst-center-api/',
    'ACI': 'https://apis.apis.io/apis/cisco/aci-api/',
    'ISE': 'https://apis.apis.io/apis/cisco/ise-api/',
    'Intersight': 'https://apis.apis.io/apis/cisco/intersight-api/',
    'SD-WAN': 'https://apis.apis.io/apis/cisco/sdwan-api/',
    'ThousandEyes': 'https://apis.apis.io/apis/cisco/thousandeyes-api/',
}


def main():
    seen = set()
    n_unique = 0
    for ln in LINES:
        for (st, _) in ln["stations"]:
            if st not in seen:
                n_unique += 1
                seen.add(st)
    build_subway(
        title='The Cisco API · Underground Map',
        subtitle=f"{n_unique} APIs · {len(LINES)} functional lines · click any station for the apis.io page",
        lines=LINES,
        abbrev=ABBREV,
        source_label='Source: cisco/openapi · github.com/api-evangelist/cisco',
        out_dir=Path(__file__).resolve().parent,
        out_basename='cisco-subway-map',
        provider_id='cisco',
        station_url_overrides=URL_OVERRIDES,
    )


if __name__ == "__main__":
    main()
